name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Run tests
        run: yarn test

  ios:
    name: iOS tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler: '2.2.27'
      - name: Install npm dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts
      - name: Install Example npm dependencies
        run: yarn --frozen-lockfile --non-interactive --silent
        working-directory: ./Example
      - name: Install Example gem dependencies
        working-directory: ./Example
        run: bundle install
      - name: Install Example cocoapods dependencies
        working-directory: ./Example/ios
        run: bundle exec pod install
      - name: Run tests
        run: yarn test-ios
